export type Speciality = {
    ANESTHESIOLOGY:"Anestesiología",
    CARDIOLOGY:"Cardiología",
    GENERAL_SURGERY:"Cirugía General",
    PLASTIC_SURGERY:"Cirugía Plástica",
    DERMATOLOGY:"Dermatología",
    ENDOCRINOLOGY:"Endocrinología",
    GASTROENTEROLOGY:"Gastroenterología",
    GERIATRICS:"Geriatría",
    GYNECOLOGY_AND_OBSTETRICS:"Ginecología y Obstetricia",
    HEMATOLOGY:"Hematología",
    INFECTIOUS_DISEASE:"Enfermedades Infecciosas",
    FAMILY_AND_GENERAL_MEDICINE:"Medicina Familiar y General",
    INTERNAL_MEDICINE:"Medicina Interna",
    NEPHROLOGY:"Nefrología",
    PULMONOLOGY:"Neumología",
    NEUROSURGERY:"Neurocirugía",
    NEUROLOGY:"Neurología",
    NUTRITION:"Nutrición",
    OPHTHALMOLOGY:"Oftalmología",
    ONCOLOGY:"Oncología",
    ORTHOPEDICS_AND_TRAUMATOLOGY:"Ortopedia y Traumatología",
    OTORHINOLARYNGOLOGY:"Otorrinolaringología",
    PEDIATRICS:"Pediatría",
    PSYCHIATRY:"Psiquiatría",
    RADIOLOGY:"Radiología",
    RHEUMATOLOGY:"Reumatología",
    UROLOGY:"Urología"
}